language: php
dist: xenial

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - name: "Backward compatibility check"
  include:
    - php: 7.1
      name: "Coding standard check"
      script: vendor/bin/phpcs
      before_install: phpenv config-rm xdebug.ini
      after_success: skip
    - php: 7.4
      name: "PHPStan"
      script: vendor/bin/phpstan analyze
      before_install: phpenv config-rm xdebug.ini
      after_success: skip
    - php: 7.1
      name: "phpmyadmin/motranslator"
      install:
        - composer require "phpmyadmin/motranslator:^3.0"
        - composer install --no-interaction
      after_success:
        - bash <(curl -s https://codecov.io/bash) -F motranslator
    - php: 7.2
      name: "API docs"
      before_install: phpenv config-rm xdebug.ini
      after_success: skip
      install:
        - composer global require "code-lts/doctum:^5.0"
        - composer install --no-interaction
      script:
        - $HOME/.composer/vendor/bin/doctum.php --no-interaction update ./tools/doctum-config.php
    - php: nightly
      install:
        - composer install --no-interaction --ignore-platform-reqs
    - php: 7.4
      name: "Backward compatibility check"
      before_install: phpenv config-rm xdebug.ini
      after_success: skip
      install:
        - composer require --dev roave/backward-compatibility-check
        - composer install --no-interaction
      script:
        - vendor/bin/roave-backward-compatibility-check

install:
  - composer install --no-interaction

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ -f build/logs/clover.xml ] ; then curl -LsO https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi

cache:
  directories:
    - $HOME/.composer/cache

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist
