language: php

cache:
    directories:
        - vendor
        - $HOME/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini

before_script:
    - composer install

script:
    - composer run phpunit

matrix:
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: 7.4
        - php: nightly
          before_install: skip
          before_script:
              - composer install --ignore-platform-reqs
    fast_finish: true
